# Generated by Django 5.2.9 on 2025-12-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='moodtracker_entry',
        ),
    ]
